# Schema for the configuration files of the Claro Alter theme.

claroalter.settings:
  type: theme_settings
  label: 'claro alter settings'
  mapping:
    base_primary_color:
      type: color_hex
      label: 'Base Primary Color'
